In [2]:
import numpy as np

In [5]:
matrix=[[4,1,2],[3,5,1],[1,1,3]]
#  4   1  2      4
#  3   5  1  =   7
#  1   1  3      3 
​

In [24]:
diag=np.diag(np.abs(matrix))

In [25]:
off_diag_sum=np.sum(matrix,axis=1)

In [26]:
off_diag_sum

array([7, 9, 5])

In [27]:
off_diag=np.sum(matrix,axis=1)-diag

In [28]:
off_diag

array([3, 4, 2])

In [31]:
if np.all(diag>off_diag): #Cheching Diagnal is Dominant or note
    print("The diagnal is dominanat")
else:
    print("The diagnol is not dominant")

The diagnal is dominanat


In [32]:
matrix

[[4, 1, 2], [3, 5, 1], [1, 1, 3]]

In [59]:
x1=0  
x2=0     #We will start with some guess.Here ()we use 0 as guess
x3=0
x_old=np.array([x1,x2,x3])
elipson=0.001
coverage=False
for k in range(50):
    x1= (4-x2-2*x3)/4
    x2=(7-3*x1-x3)/5
    x3=(3-x1-x2)/3
    x=np.array([x1,x2,x3])
    diff=np.sqrt(np.dot(x-x_old,x-x_old))
    if(diff<elipson):
        print("Coverage")
        Coverage=True
        break
    else:
        print("%d   %.4f   %.4f   %.4f "% (k,x1,x2,x3))
        x_old=x

0   1.0000   0.8000   0.4000 
1   0.6000   0.9600   0.4800 
2   0.5200   0.9920   0.4960 
3   0.5040   0.9984   0.4992 
4   0.5008   0.9997   0.4998 
Coverage


In [60]:
x_old

array([0.5008 , 0.99968, 0.49984])